version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: deployments/docker/Dockerfile.backend
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    volumes:
      - ${UPLOADS_DIR:-../uploads}:/app/uploads
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://ollama:11434}
    depends_on:
      - ollama

  frontend:
    build:
      context: ..
      dockerfile: deployments/docker/Dockerfile.frontend
    ports:
      - "${FRONTEND_PORT:-8501}:8501"
    environment:
      - BACKEND_URL=http://backend:${BACKEND_PORT:-8000}
    depends_on:
      - backend

  ollama:
    image: ollama/ollama:latest
    ports:
      - "${OLLAMA_PORT:-11434}:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  ollama_data:
