services:
  backend:
    build:
      context: ..
      dockerfile: deployments/docker/Dockerfile.backend
    container_name: backend
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    volumes:
      - ${UPLOADS_DIR:-./uploads}:/app/backend/uploads
      - shared_uploads:/app/backend/upload
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - ollama

  frontend:
    build:
      context: ..
      dockerfile: deployments/docker/Dockerfile.frontend
    container_name: frontend
    ports:
      - "${FRONTEND_PORT:-8501}:8501"
    volumes:
      - shared_uploads:/app/frontend/upload
    environment:
      - BACKEND_URL=http://backend:${BACKEND_PORT:-8000}
    depends_on:
      - backend

  ollama:
    build:
      context: ./docker/ollama
      dockerfile: Dockerfile.ollama
    container_name: ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "${OLLAMA_PORT:-11434}:11434"

volumes:
  ollama_data:
  shared_uploads:
