[general]
project_name = "llm-rag-oppen"
upload_dir = "uploads"
webhook_url = "http://localhost:8501/webhook"
backend_port = 8000
frontend_port = 8501

[logging]
LEVEL = "INFO"
FILE = "app.log"
ROTATION = "500 MB"
RETENTION = "10 days"

[llm]
PROVIDER = "ollama"

[llm.PROVIDERS.ollama]
NAME = "llama3.1:8b"
BASE_URL = "http://192.168.1.7:11434"
API_KEY = ""

[llm.PROVIDERS.openai]
NAME = "gpt-4"
BASE_URL = "https://api.openai.com/v1"
API_KEY = "your-openai-api-key"

[embedding]
PROVIDER = "ollama"

[embedding.PROVIDERS.ollama]
NAME = "llama3.1:8b"
BASE_URL = "http://192.168.1.7:11434"
API_KEY = ""

[embedding.PROVIDERS.openai]
NAME = "text-embedding-ada-002"
BASE_URL = "https://api.openai.com/v1"
API_KEY = "your-openai-api-key"

[wandb]
wandb_api_key = "1f389e5c78e7cea9d2078e26d5776dfa8ee6querd"
