# deployments/docker/Dockerfile.frontend
FROM python:3.10-slim AS builder

WORKDIR /app

# Install uv
RUN pip install --no-cache-dir uv

# Copy only the requirements file first to leverage Docker cache
COPY frontend/requirements.txt .

# Create a virtual environment and install dependencies
RUN uv venv && \
    . .venv/bin/activate && \
    uv pip install --no-cache-dir -r requirements.txt

# Final stage
FROM python:3.10-slim

WORKDIR /app

RUN groupadd -g 1000 lsgroup && \
    useradd -u 1000 -g lsgroup -s /bin/bash -m lsuser

RUN mkdir -p /app/backend/upload && chown -R lsuser:lsgroup /app
# Copy the virtual environment from the builder stage
COPY --from=builder /app/.venv /app/.venv

# Copy the application code
COPY frontend/ .

# Set the PATH to use the virtual environment by default
ENV PATH="/app/.venv/bin:$PATH"

# Run the application
CMD ["streamlit", "run", "home.py"]
